# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: MacOS

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '**.md'

jobs:
  macos_acceptance:
    name: MacOS
    uses: ./.github/workflows/tests_reusable.yml
    with:
      # arrays for matrices must be given as string for json parsing
      # https://github.community/t/reusable-workflow-with-strategy-matrix/205676
      os: '["macos-latest"]'
      browser: '["chrome", "edge", "safari"]'
      python-version: '["3.8", "3.9"]'
      rfw-322-python: "3.8"
      additional-rfw-parameters: "-e RESOLUTION_DEPENDENCY -e FLASK"