# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Quality Assurance

on: 
  push:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ master, main ]
    paths-ignore:
      - '**.md'

jobs:
  StaticAnalysis:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      # This job must pass for the test jobs to run 
      # --> check the execution flag on each step
      # Is there a better way to skip execution and mark job as passed?
      if: ${{ github.event.inputs.StaticAnalysis == 'true' || github.event.inputs.StaticAnalysis == null }}
      uses: actions/checkout@v2
    - name: Set up Python
      if: ${{ github.event.inputs.StaticAnalysis == 'true' || github.event.inputs.StaticAnalysis == null }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      if: ${{ github.event.inputs.StaticAnalysis == 'true' || github.event.inputs.StaticAnalysis == null }}
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt

    - name: Typecheck with mypy
      if: ${{ github.event.inputs.StaticAnalysis == 'true' || github.event.inputs.StaticAnalysis == null }}
      run: |
        mypy --show-error-codes QWeb

    - name: Lint with flake8
      if: ${{ github.event.inputs.StaticAnalysis == 'true' || github.event.inputs.StaticAnalysis == null }}
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Lint with pylint
      if: ${{ github.event.inputs.StaticAnalysis == 'true' || github.event.inputs.StaticAnalysis == null }}
      run: |
        pylint QWeb
